//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FastFoodRestaurant.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ITEM
    {
        public int ITEM_ID { get; set; }
        [Display(Name = "*Item Category")]
        [Required(ErrorMessage = "Category is required")]
        public Nullable<int> CAT_ID { get; set; }

        [Display(Name = "*Item Name")]
        [Required(ErrorMessage = "Name is required")]
        [StringLength(50, ErrorMessage = "Name can be 50 characters long at max")]
        public string NAME { get; set; }

        [StringLength(500,ErrorMessage ="Description exceeds 500 character limit")]
        [Display(Name = "Item Description")]
        public string DESCRIPTION { get; set; }

        [Display(Name = "*Item Price (PKR)")]
        [Required(ErrorMessage = "Price is required")]
        [Range(1,1000000,ErrorMessage ="Price not in range (1-1000000)")]
        public decimal PRICE { get; set; }

        [Display(Name = "*Item Image")]
        public string PICTURE { get; set; }

        public virtual CATEGORY CATEGORY { get; set; }
    }
}
